### ISSUE TITLE
torch.argmax doesn't have axis argument

### ISSUE THREAD

**Issue by kwalcock** [clulab/scala-transformers#30]
I"m getting an error message
```
evaluator.py:47: error: Unexpected keyword argument "axis" for "argmax"  [call-arg]
```
coming from the current code at
https://github.com/clulab/scala-transformers/blob/01939a16582146f56e4225555c962ae1ebc66180/encoder/src/main/python/evaluator.py#L46

that was translated from
https://github.com/clulab/scala-transformers/blob/5bff7aadb6aaae43c48227100e994325b405c7b4/encoder/src/main/python/evaluation_metrics.py#L60

This isn't the only instance.  Can the argument be removed?

**Comment by MihaiSurdeanu** [comment]
No, I don't think it can be removed... It should be replaced with a value for the `dim` parameter:
https://pytorch.org/docs/stable/generated/torch.argmax.html

I wonder why this worked before? Did you switch to PyTorch 2?

**Comment by kwalcock** [comment]
It isn't crashing or anything.  Type checkers, in this case mypy, are flagging it as incorrect.  This [documentation](https://pytorch.org/docs/stable/generated/torch.argmax.html) doesn't show an axis.

**Comment by MihaiSurdeanu** [comment]
Fwiw, the code works as is. I just tried it with an existing model. 
So we know that that parameter does not hurt. Maybe it is indeed not needed. I will check soon(ish).

**Comment by MihaiSurdeanu** [comment]
I commented out the `axis = -1`, and the code fails with this error:
```
Traceback (most recent call last):
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/averager.py", line 129, in <module>
    main()
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/averager.py", line 36, in main
    all_checkpoints = evaluate_checkpoints(model, tasks)
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/averager.py", line 60, in evaluate_checkpoints
    macro_acc = evaluate_model(model, tasks)
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/evaluation_metrics.py", line 102, in evaluate_model
    ner_acc = evaluate_with_model(model, tasks[0])
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/evaluation_metrics.py", line 96, in evaluate_with_model
    acc = evaluation_classification_report(model, task, task.task_name, useTest = False)
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/evaluation_metrics.py", line 77, in evaluation_classification_report
    golds, predictions = predict(model, ds)
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/evaluation_metrics.py", line 63, in predict
    predictions.extend(pred_labels.tolist())
TypeError: 'int' object is not iterable
```

**Comment by kwalcock** [comment]
That's unexpected.  I'll try to check at runtime to see what the arguments really are and what undocumented code is running.

**Comment by kwalcock** [comment]
The code is running on my computer now and I can verify this.  I believe pytorch is not using the named parameter but passing them through to numpy, which does have an [axis](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html).
