### ISSUE TITLE
URGENT: clu_trainer crashes

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/scala-transformers#39]
This command now fails as follows:

```
PYTHONHASHSEED=1 python encoder/src/main/python/clu_trainer.py
...
Elapsed training time: 0:00:01.409770
Traceback (most recent call last):
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/clu_trainer.py", line 96, in <module>
    CluTrainer(tokenizer).train(tasks)
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/clu_trainer.py", line 63, in train
    CluTimer.time(
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/clu_timer.py", line 11, in time
    func()
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/clu_trainer.py", line 64, in <lambda>
    lambda: trainer.train()
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/transformers/trainer.py", line 1500, in train
    return inner_training_loop(
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/transformers/trainer.py", line 1742, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/transformers/trainer.py", line 2486, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/transformers/trainer.py", line 2518, in compute_loss
    outputs = model(**inputs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/msurdeanu/github/scala-transformers/encoder/src/main/python/token_classifier.py", line 48, in forward
    outputs = self.encoder(
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 1101, in forward
    encoder_outputs = self.encoder(
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 542, in forward
    output_states = layer_module(
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 386, in forward
    attention_output = self.attention(
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 317, in forward
    self_output = self.self(
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_deberta_v2.py", line 733, in forward
    query_layer = self.transpose_for_scores(self.query_proj(query_states), self.num_attention_heads)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/msurdeanu/miniconda3/envs/t/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

(This was on rogue)
@kwalcock : this is blocking me from training new models. Can you please look into it?
I will send the new data over email.
Thank you!

**Comment by MihaiSurdeanu** [comment]
Nm. I think I figured out the problem. Please ignore.
